### ISSUE TITLE
[View]Community -> BoardTextDetail

### ISSUE THREAD

**Issue by dongjin97** [GNU-CORNER/BookkyProject_iOS#32]
## View Issue
커뮤니티에서 글 클릭시 전환되는 View
-글이 있는 게시판 이름
-글 제목
-글 을 본사람의수
-글을 쓴 UserImage&Name
-글 내용
-글에 대한 좋아요 개수
-글에 대한 댓글 개수
-댓글 단 유저이름 ,적은 내용 ,적은 날짜 ,공감 , 추가 기능 버튼UI,
-댓글 작성
-댓글 수정,삭제
-대댓글
##Q&A
-Q&A 부분 따로 구현 필요
-Q&A 답글 ,댓글 ,댓글에 대한 대댓글
## All 
- 댓글 수정 ,삭제,신고를 위한 ActionSheet , 대댓글 작성 ,수정, 삭제 신고를 위한 ActionSheet 
- 글  수정 삭제 ActionSheet 
- 답글  수정 삭제 ActionSheet 
- Q&A 이미지 추가뷰
- Q&A 책 추가뷰
- 일반 글 이미지 추가뷰
- 일반글 책 추가뷰
## ToDo
- [x] ~BoardName
- [x] ~TextTittle
- [x] ~TextViewUserCount
- [x] ~WriteTextUserName&Image
- [x] ~TextContent
- [x] ~TextLikeThatCount
- [x] ~TextCommnetCount
- [x] ~TextCommentUI (UserName , contents,likeTharCount, addFunction )
- [x] ~TextComment Write
- [x] ~TextreplyComment
- [x] ~TextComment delete/Chage - Action sheet
## Q&A
- [x] Q&A 게시판 글
- [x] Q&A 답글
- [x] Q&A 댓글
- [x]  Q&A 답글에 대한 댓글
- [x] Q&A 대댓글
## All 
- [x] - 댓글 수정 ,삭제,신고를 위한 ActionSheet , 대댓글 작성 ,수정, 삭제 신고를 위한 ActionSheet 
- [x] - 글  수정 삭제 ActionSheet 
- [x] - 답글  수정 삭제 ActionSheet 
- [x] - Q&A 이미지 추가뷰
- [x] - Q&A 책 추가뷰
- [x] - 일반 글 이미지 추가뷰
- [x] - 일반글 책 추가뷰
