### ISSUE TITLE
[Feat]Community -> BoardTextDetail

### ISSUE THREAD

**Issue by dongjin97** [GNU-CORNER/BookkyProject_iOS#33]
## Feature Issue
-선택된 글에 대한 PID
-선택된 글에 대한 DetailView의 데이터
-글의 좋아요 버튼 클릭시 좋아요수증가
-댓글 작성,수정,삭제
-댓글 공감 클릭시 카운증가
-대댓글
-대댓글 수정 삭제 작성
-QnA  게시글 ,답글 ,댓글 대댓글 ,  작성,수정, 삭제
## ToDo
- [x] ~tapText Get PID
- [x] ~getBoardText Get Content
- [x] ~WriteText User Name&Image
- [x] ~BoarText LikeCount
- [x] ~GetComment
- [ ] ~textDetailLikeCount ++
- [ ] ~CommentLikeCount ++ 
- [ ] ~WriteComment
- [ ] ~deleteComment
- [ ] ~changeComment
- [ ] ~대댓글
- [ ] ~대댓글 작성 ,수정 ,삭제
## Q&A
- [ ] ~게시글 
- [ ] ~게시글  작성
- [ ] ~게시글  수정/삭제
- [ ] ~답글
- [ ] ~답글 작성
- [ ] ~답글 수정/삭제
- [ ] ~댓글 
- [ ] ~댓글 작성
- [ ] ~댓글 수정/삭제
- [ ] ~대댓글
- [ ] ~대댓글 작성
- [ ] ~대댓글 수정 삭제
