### ISSUE TITLE
[Feat/View] BookDetail view

### ISSUE THREAD

**Issue by dahae0320** [GNU-CORNER/BookkyProject_iOS#41]
## Feature, View Issue
Implement BookDetail view.

## ToDo
- [x] 책썸네일, 관련 태그
- [x] 도서정보
- [x] 책 소개
- [x] 리뷰UI및 데이터 GET
- [x] 서버에서 책디테일 데이터 GET
- [x] 태그 리스트 클릭시 태그에 해당하는 도서목록 출력
## 향후 고쳐야할 문제
- [x] 오토레이아웃 이슈 해결 밑에 리뷰 테이블뷰 constraint 수정필요
## 리뷰 
- [x] 리뷰 작성 View
- [x] 리뷰 쓰기
- [x] 리뷰 수정
- [x] 리뷰 삭제
- [x] 리뷰 좋아요

**Comment by dongjin97** [comment]
북상세정보 오토레이아웃이슈를 제외한 모든 기능구현완료
