### ISSUE TITLE
[HotFix] 잠시 썸네일 이미지 주석 처리 

### ISSUE THREAD

**Issue by dahae0320** [GNU-CORNER/BookkyProject_iOS#84]
## HotFix Issue
학과 건물 공사로 인해 학과 서버가 옮겨졌다. 그래서 당분간 서버 URL이 바뀌는데, 썸네일 스토리지 서버는 바꾸려면 더 길어진다고 해서(공사 끝나면 다시 복구되는데 굳이!) 임의로 썸네일 부분의 코드를 주석 처리 합니당.

## ToDo
- [ ] MyProfileViewController: user thumbnail [85 ~ 97]
- [ ] MyProfileViewController: my books thumbnail [266 ~ 273]
- [ ] MyProfileViewController: my reviews book thumbnail [301 ~ 308]
- [ ] MyReviewsMoreViewController: my detail reviews book thumbnail [78 ~ 85]

**Comment by dahae0320** [comment]
라고 커밋올리는 순간 BE에서 해결해주심.~~~
